services:
  postgres:
    image: postgres
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
    ports:
      - "5432:5432"